// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3PBo8vWeHL_tgQ0P-XdWk4iWXHefGVk',
    appId: '1:927092219486:web:14c1342b30e2ab0bcb5ecf',
    messagingSenderId: '927092219486',
    projectId: 'food-deilivery',
    authDomain: 'food-deilivery.firebaseapp.com',
    storageBucket: 'food-deilivery.appspot.com',
    measurementId: 'G-BGQSMYJHNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_DODqKHfliP38jskzCMuyN-4JMey8tU',
    appId: '1:927092219486:android:96c8399262b67faccb5ecf',
    messagingSenderId: '927092219486',
    projectId: 'food-deilivery',
    storageBucket: 'food-deilivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAlKVHBj2tyeCaI-Mt60FZRHxpY8UA9BY',
    appId: '1:927092219486:ios:4d7f2c3fa3c62dfdcb5ecf',
    messagingSenderId: '927092219486',
    projectId: 'food-deilivery',
    storageBucket: 'food-deilivery.appspot.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAlKVHBj2tyeCaI-Mt60FZRHxpY8UA9BY',
    appId: '1:927092219486:ios:4d7f2c3fa3c62dfdcb5ecf',
    messagingSenderId: '927092219486',
    projectId: 'food-deilivery',
    storageBucket: 'food-deilivery.appspot.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv3PBo8vWeHL_tgQ0P-XdWk4iWXHefGVk',
    appId: '1:927092219486:web:1d4759de4e1d12a0cb5ecf',
    messagingSenderId: '927092219486',
    projectId: 'food-deilivery',
    authDomain: 'food-deilivery.firebaseapp.com',
    storageBucket: 'food-deilivery.appspot.com',
    measurementId: 'G-J53BW9RHPX',
  );
}
